title: 'Build copilots with Azure Cosmos DB'
theme: just-the-docs
enable_copy_code_button: true
heading_anchors: true
nav_enabled: true
back_to_top: true
back_to_top_text: "Back to top"
baseurl: /microsoft-learning-path-build-copilots-with-cosmos-db-labs
exclude:
  - readme.md
  - .github/
aux_links:
  "Build copilots with Azure Cosmos DB": 
    - "https://github.com/solliancenet/microsoft-learning-path-build-copilots-with-cosmos-db-labs"
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
# header_pages:
#   - index.html
author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : false